# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Téléchargement de la nouvelle version
        uses: actions/checkout@v3
      - name: Mise en place des pages
        uses: actions/configure-pages@v2
     
      - name: Installation des dépendances
        run: sudo apt-get install -y pandoc texlive texlive-latex-base texlive-latex-extra
      
      - name: Compilation des PDF
        run: |
          find * -type d -exec mkdir -p ../out/{} \;
          find . -type f -name "*.md" -exec bash -c 'pandoc -V geometry:margin=2cm --toc -s -f markdown+tex_math_dollars --resource-path="./$(dirname {})" --mathjax "{}" --output="../out/$(basename -s .md {}).pdf"' \;
      - name: Compilation des pages HTML du site
        run: |
          find * -type d -exec mkdir -p ../out-html/{} \;
          find . -type f -name "*.md" -exec bash -c 'pandoc -V geometry:margin=2cm --toc -s -f markdown+tex_math_dollars --resource-path="./$(dirname {})" --title=$(basename -s .md {}) --mathjax "{}" --output="../out-html/$(basename -s .md {}).html"' \;

      - name: Création du ZIP des cours en PDF
        uses: actions/upload-artifact@v3
        with:
          path: ${{github.workspace}}/out
          name: 'Cours imprimés en PDF'
      - name: Création du ZIP des cours en HTML
        uses: actions/upload-artifact@v3
        with:
          path: ${{github.workspace}}/out-html
          name: 'Cours en format HTML'

      - name: Téleversement des pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: '../out-html'
      - name: Mise en ligne des pages
        id: deployment
        uses: actions/deploy-pages@v1
